# Generated by Django 4.0.1 on 2022-12-12 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tannin', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('sweetness', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('acidity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('alcohol', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('body', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('recommend', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regions_and_flags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='fr', max_length=3)),
                ('country', models.CharField(blank=True, default='France', max_length=150)),
                ('continent', models.CharField(blank=True, default='Europe', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wine_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grapes_list', models.CharField(blank=True, choices=[('Cabernet Sauvignon', 'Cabernet Sauvignon'), ('Chardonnay', 'Chardonnay'), ('Grenache', 'Grenache'), ('Malbec', 'Malbec'), ('Merlot', 'Merlot'), ('Pinot Noir', 'Pino Noir'), ('Riesling', 'Riesling'), ('Sauvignon Blanc', 'Sauvignon Blanc'), ('Shiraz/Syrah', 'Shiraz/Syrah')], default='Cabernet Sauvignon', max_length=20)),
                ('winery_name', models.CharField(blank=True, max_length=100)),
                ('special_grapes', models.CharField(blank=True, max_length=100)),
                ('continent', models.CharField(choices=[('Africa', 'Africa'), ('North America', 'North America'), ('South America', 'South America'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('Oceania', 'Oceania')], default='Europe', max_length=15)),
                ('type', models.CharField(choices=[('Red Dry', 'Red Dry'), ('Red Semi Sweet', 'Red Semi Sweet'), ('Red Sweet', 'Red Sweet'), ('White Dry', 'White Dry'), ('White Semi Sweet', 'White Semi Sweet'), ('White Sweet', 'White Sweet'), ('Sparkling', 'Sparkling'), ('Rose', 'Rose')], default='Red Dry', max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=300)),
                ('video_url', models.CharField(blank=True, max_length=300)),
                ('post_created_date', models.DateField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine_blog.regions_and_flags')),
                ('rating_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_id', to='wine_blog.personal_rating')),
            ],
        ),
    ]
